### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by dylanoy** [emilkm/amfext#2]
/configure: line 4239: PHP_AMF_SETUP_AMF_CHECKER: command not found

**Comment by dylanoy** [comment]
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local
checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/lib/php/extensions/no-debug-non-zts-20160303
checking for PHP installed headers prefix... /usr/local/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.14.3 (ok)
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable AMF Serialization support... yes, shared
checking for ANSI C header files... yes
**# ./configure: line 4239: PHP_AMF_SETUP_AMF_CHECKER: command not found**
checking for ld used by cc... /usr/x86_64-alpine-linux-musl/bin/ld
checking if the linker (/usr/x86_64-alpine-linux-musl/bin/ld) is GNU ld... yes
checking for /usr/x86_64-alpine-linux-musl/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes

**Comment by emilkm** [comment]
What system are you trying to build on? What was the command you executed?

You can try with simple config.m4

```
PHP_ARG_ENABLE(amf, wether to enable AMF Serialization support,
[  --enable-amf          Enable AMF Serialization support])

if test "$PHP_AMF" != "no"; then
  PHP_NEW_EXTENSION(amf, amf.c, $ext_shared)
  PHP_SUBST(AMF_SHARED_LIBADD)
  AC_DEFINE([HAVE_AMF], 1, [Wether you have AMF])
fi
`
