### ISSUE TITLE
Invalid output when serializing a ByteArray > 128 bytes

### ISSUE THREAD

**Issue by NullSquatch** [emilkm/amfext#3]
Serializing the following produces incorrect output:

``` php
$obj = new stdClass();
$obj->value1 = new ByteArray(str_repeat("1", 129));
$obj->value2 = new ByteArray("2");
```

Expected Output:

``` hex
00000000: 110a 0b01 0d76 616c 7565 310c 8203 3131  .....value1...11
00000010: 3131 3131 3131 3131 3131 3131 3131 3131  1111111111111111
00000020: 3131 3131 3131 3131 3131 3131 3131 3131  1111111111111111
00000030: 3131 3131 3131 3131 3131 3131 3131 3131  1111111111111111
00000040: 3131 3131 3131 3131 3131 3131 3131 3131  1111111111111111
00000050: 3131 3131 3131 3131 3131 3131 3131 3131  1111111111111111
00000060: 3131 3131 3131 3131 3131 3131 3131 3131  1111111111111111
00000070: 3131 3131 3131 3131 3131 3131 3131 3131  1111111111111111
00000080: 3131 3131 3131 3131 3131 3131 3131 310d  111111111111111.
00000090: 7661 6c75 6532 0c03 3201 0a              value2..2..
```

Actual Output:

``` hex
00000000: 110a 0b01 0d76 616c 7565 310c 8203 320d  .....value1...2.
00000010: 7661 6c75 6532 0c03 3201 0000 0008 0808  value2..2.......
00000020: 5031 ea2e e37f 0000 0000 0000 0000 0000  P1..............
00000030: 0000 0000 0000 0000 5300 0000 0008 0808  ........S.......
00000040: 5031 ea2e e37f 0000 0000 0000 0000 0000  P1..............
00000050: 0000 0000 0000 0000 9100 0000 0008 0808  ................
00000060: 5031 ea2e e37f 0000 0000 0000 0000 0000  P1..............
00000070: 0000 0000 0000 0000 af00 0000 0008 0808  ................
00000080: 106f ef2e e37f 0000 0000 0000 0000 0000  .o..............
00000090: 0000 0000 ffff ffff e900 0a              ...........
```

ℹ️ NOTE: Enabling the `#define amf_NO_ZVAL_STRING_BUILDER` macro seems to remedy the issue, but I don't know for sure what side effects this might cause.

**Comment by emilkm** [comment]
It is working now. 

Just curious, what do you intend using the library with/for?

**Comment by NullSquatch** [comment]
>It is working now.

Thanks for fixing this.  I can confirm that this is working for me as well.

I may have found another bug with ByteArray serialization, but I'll report that as a separate issue because it occurs both before and after your changes here.

>Just curious, what do you intend using the library with/for?

I recently had to move a legacy AMFPHP-based application from PHP5.5 to PHP7.

It was previously using `amfext` from a different source, which stopped working after the upgrade to PHP7 due to what I'm assuming were changes to PHP's extension API.

Your version of this extension was the only one I could find that had been updated to work with PHP7.  It appears to drop support for resource types (such as result sets), but since I've never needed to serialize those directly it doesn't affect me.  There were also minor changes I had to make to the arguments that `amfphp` passed to `amfext`, such as adjusting the encoding/decoding bits and using a userland array instead of a callback.

**Comment by emilkm** [comment]
Thanks. Great to hear the extension is useful to someone else. 

You are welcome to try https://github.com/emilkm/efxphp. I have recently converted a large application from a variant of AMFPHP 1.9 to EFXPHP and it was not as hard as I thought it would be.
